/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class ImagesRes {
  ImagesRes._();

  static const String PLUGIN_NAME = 'constructionapp';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String A_DOT_BURR = 'images/a_dot_burr.jpeg';
  static const String A_DOT_HAM = 'images/a_dot_ham.jpeg';
}
