// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqzfJVOQeCklQXwOoV3KubsN6n99kJk5U',
    appId: '1:243194716935:web:0a77c6752286b5a430dba2',
    messagingSenderId: '243194716935',
    projectId: 'construction-app-16da5',
    authDomain: 'construction-app-16da5.firebaseapp.com',
    storageBucket: 'construction-app-16da5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE5xB_XFcBcbLCVi7MmcmOEs9NMdMohIU',
    appId: '1:243194716935:android:5a9130b6a69bffca30dba2',
    messagingSenderId: '243194716935',
    projectId: 'construction-app-16da5',
    storageBucket: 'construction-app-16da5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy2QHPN4qrwKz2KGOxLKEg-2ixlh1zNQk',
    appId: '1:243194716935:ios:ec9e2c75c71dfb3030dba2',
    messagingSenderId: '243194716935',
    projectId: 'construction-app-16da5',
    storageBucket: 'construction-app-16da5.firebasestorage.app',
    iosBundleId: 'com.example.constructionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy2QHPN4qrwKz2KGOxLKEg-2ixlh1zNQk',
    appId: '1:243194716935:ios:ec9e2c75c71dfb3030dba2',
    messagingSenderId: '243194716935',
    projectId: 'construction-app-16da5',
    storageBucket: 'construction-app-16da5.firebasestorage.app',
    iosBundleId: 'com.example.constructionapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqzfJVOQeCklQXwOoV3KubsN6n99kJk5U',
    appId: '1:243194716935:web:38516e8df4dd21b030dba2',
    messagingSenderId: '243194716935',
    projectId: 'construction-app-16da5',
    authDomain: 'construction-app-16da5.firebaseapp.com',
    storageBucket: 'construction-app-16da5.firebasestorage.app',
  );
}
